Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 148, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 142, in _path_stat
FileNotFoundError: [Errno 2] No such file or directory: '/home/elba_ro/.local/lib/python3.8/site-packages/semantic_version/__init__.cpython-38-x86_64-linux-gnu.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/style_transfer_trainer.py", line 3, in <module>
    from comet_ml import Experiment
  File "/home/elba_ro/.local/lib/python3.8/site-packages/comet_ml/__init__.py", line 25, in <module>
    from ._online import ExistingExperiment, Experiment
  File "/home/elba_ro/.local/lib/python3.8/site-packages/comet_ml/_online.py", line 32, in <module>
    from .artifacts import (
  File "/home/elba_ro/.local/lib/python3.8/site-packages/comet_ml/artifacts.py", line 25, in <module>
    import semantic_version
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1407, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1379, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1525, in find_spec
  File "<frozen importlib._bootstrap_external>", line 156, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 148, in _path_is_mode_type
KeyboardInterrupt
/home/elba_ro/.local/lib/python3.8/site-packages/scipy/__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "
| ID | GPU | MEM |
------------------
|  0 | 92% | 83% |
|  1 |  0% |  0% |
None
dotenv was True
Token is valid.
[1m[31mCannot authenticate through git-credential as no helper is defined on your machine.
You might have to re-authenticate when pushing to the Hugging Face Hub.
Run the following command in your terminal in case you want to set the 'store' credential helper as default.

git config --global credential.helper store

Read https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage for more details.[0m
Token has not been saved to git credential helper.
Your token has been saved to /home/elba_ro/.cache/huggingface/token
Login successful
Running Experiments for key style_estyle_evaluator_liberal_bb/styles/bb
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/elba_ro/repos/github/conf22-style-transfer/scripts/style_transfer_trai │
│ ner.py:62 in run_experiment                                                  │
│                                                                              │
│    59 │   │                                                                  │
│    60 │   │   login(os.getenv('HUGGINGFACE_TOKEN'), add_to_git_credential=Tr │
│    61 │   │   print(f"Running Experiments for key {config_key}")             │
│ ❱  62 │   │   config_dict = all_configs[config_key]                          │
│    63 │   │   print(config_dict["output_dir"].split("/")[-1].replace("_", "" │
│    64 │   │   experiment = init_comet(config_dict["output_dir"].split("/")[- │
│    65                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
KeyError: 'style_estyle_evaluator_liberal_bb/styles/bb'

During handling of the above exception, another exception occurred:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/elba_ro/repos/github/conf22-style-transfer/scripts/style_transfer_trai │
│ ner.py:129 in main                                                           │
│                                                                              │
│   126 │   │   parser.add_argument("-k", "--experimentkey", type=str)         │
│   127 │   │   args = parser.parse_args()                                     │
│   128 │   │                                                                  │
│ ❱ 129 │   │   run_experiment(args.experimentkey)                             │
│   130 │   finally:                                                           │
│   131 │   │   #tracker.stop()                                                │
│   132 │   │   global experiment                                              │
│                                                                              │
│ /home/elba_ro/repos/github/conf22-style-transfer/scripts/style_transfer_trai │
│ ner.py:117 in run_experiment                                                 │
│                                                                              │
│   114 │   │   │   experiment.log_metric("test_score", score)                 │
│   115 │                                                                      │
│   116 │   finally:                                                           │
│ ❱ 117 │   │   experiment.end()                                               │
│   118                                                                        │
│   119                                                                        │
│   120 def main():                                                            │
╰──────────────────────────────────────────────────────────────────────────────╯
NameError: name 'experiment' is not defined

During handling of the above exception, another exception occurred:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/elba_ro/repos/github/conf22-style-transfer/scripts/style_transfer_trai │
│ ner.py:137 in <module>                                                       │
│                                                                              │
│   134 │   │   #print(f"FINAL EMMISION {tracker.final_emissions}")            │
│   135                                                                        │
│   136 if __name__ == "__main__":                                             │
│ ❱ 137 │   main()                                                             │
│                                                                              │
│ /home/elba_ro/repos/github/conf22-style-transfer/scripts/style_transfer_trai │
│ ner.py:133 in main                                                           │
│                                                                              │
│   130 │   finally:                                                           │
│   131 │   │   #tracker.stop()                                                │
│   132 │   │   global experiment                                              │
│ ❱ 133 │   │   experiment.end()                                               │
│   134 │   │   #print(f"FINAL EMMISION {tracker.final_emissions}")            │
│   135                                                                        │
│   136 if __name__ == "__main__":                                             │
╰──────────────────────────────────────────────────────────────────────────────╯
NameError: name 'experiment' is not defined
